#ifndef ERRORS_H
#define ERRORS_H

typedef enum Errors
{
    NO_ERRORS = 0,
    PROC_NULL_PTR = 1,
    PROC_INVALID_STACK = 2,
    PROC_INVALID_BYTECODE = 4,
    SIZE_LT_CAPACITY = 8,
	DATA_NULL_PTR = 16,
	NEGATIVE_SIZE = 32,
	DEAD_CANARY = 64,
	STACK_UNDERFLOW = 128,
	STACK_DIV_BY_ZERO = 256,
	STACK_INVALID_ARGUMENT = 512
} Errors;

#endif
